name: Build with Nuitka

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"
  workflow_dispatch:

jobs:
  build-standalone:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            name: windows-x64
          - os: windows-11-arm
            name: windows-arm

    runs-on: ${{ matrix.os }}
    name: Nuitka Build Standalone (${{ matrix.name }})
    steps:
      - uses: actions/checkout@v3

      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true
          python-version: "3.12"

      - name: Cache Nuitka
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/Nuitka
            ~/AppData/Local/Nuitka/Nuitka
            ~/Library/Caches/Nuitka
            bongocat.build
          key: nuitka-${{ matrix.name }}
          restore-keys: |
            nuitka-${{ matrix.name }}

      - name: Build with Nuitka
        shell: pwsh
        run: |
          Remove-Item -Recurse -Force bongocat.dist -ErrorAction SilentlyContinue
          uv sync --group build
          uv run poe build standalone

      - name: List dist items
        run: Get-ChildItem -Recurse -Force .\bongocat.dist
        shell: pwsh

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          path: bongocat.dist
          name: bongo-cat-standalone-${{ matrix.name }}
          retention-days: 30

  build-onefile:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            name: windows-x64
          - os: windows-11-arm
            name: windows-arm

    runs-on: ${{ matrix.os }}
    name: Nuitka Build Onefile (${{ matrix.name }})
    steps:
      - uses: actions/checkout@v3

      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true
          python-version: "3.12"
      - name: Cache Nuitka
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/Nuitka
            ~/AppData/Local/Nuitka/Nuitka
            ~/Library/Caches/Nuitka
            rovr.build
          key: nuitka-${{ matrix.name }}
          restore-keys: |
            nuitka-${{ matrix.name }}

      - name: Build with Nuitka
        shell: pwsh
        run: |
          Remove-Item -Recurse -Force bongocat.dist -ErrorAction SilentlyContinue
          uv sync --group build
          uv run poe build onefile

      - name: Get Executable Hash
        run: Get-FileHash .\bongocat.exe -Algorithm SHA256
        shell: pwsh

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          path: bongocat.exe
          name: bongo-cat-onefile-${{ matrix.name }}
          retention-days: 30

  notify-build-success:
    runs-on: ubuntu-slim
    name: Notify Build Success
    needs: [build-standalone, build-onefile]
    steps:
      - name: Notify Discord
        uses: sarisia/actions-status-discord@v1.13.0
        with:
          webhook: ${{ secrets.LOG_HOOK }}
          title: Bongo Cat Build Success
          color: 0x00FF00
          description: |
            Download artifacts:
            - [standalone-x64](https://nightly.link/NSPC911/bongo-cat/actions/runs/${{ github.run_id }}/build-standalone/artifacts/bongo-cat-standalone-windows-x64.zip)
            - [standalone-arm](https://nightly.link/NSPC911/bongo-cat/actions/runs/${{ github.run_id }}/build-standalone/artifacts/bongo-cat-standalone-windows-arm.zip)
            - [onefile-x64](https://nightly.link/NSPC911/bongo-cat/actions/runs/${{ github.run_id }}/build-onefile/artifacts/bongo-cat-onefile-windows-x64.zip)
            - [onefile-arm](https://nightly.link/NSPC911/bongo-cat/actions/runs/${{ github.run_id }}/build-onefile/artifacts/bongo-cat-onefile-windows-arm.zip)
          avatar_url: "https://avatars.githubusercontent.com/u/176916861?v=4"
          username: "NSPBot911"
          nodetail: true
          notimestamp: true
          noprefix: true
